name: ci-dev

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Build
        run: pnpm build
